zh:
  resource:
    - title: 资源
      name: Resource
      items:
        - title: 设计资源
          name: design
  components:
    - title: 综述
      name: Docs
      items:
        - title: 介绍
          name: Introduction
        - title: 安装
          name: Installation
        - title: 快速上手
          name: Quickstart
        - title: 国际化
          name: I18n
        - title: 更新日志
          name: Changelog
    - title: 组件
      name: Docs
      groups:
        - title: 基础组件
          items:
            - title: 按钮
              name: Button
en:
  resource:
    - title: Resource
      name: Resource
      items:
        - title: Design
          name: design
  components:
    - title: Overview
      name: Docs
      items:
        - title: Introduction
          name: Introduction
        - title: Installation
          name: Installation
        - title: Quickstart
          name: Quickstart
        - title: Internationalization
          name: i18n
        - title: Change Log
          name: Changelog
    - title: Components
      name: Docs
      groups:
        - title: Base
          items:
            - title: Button
              name: Button
